app_default:
    resource: "@AppDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
